export const endpoints = {
	characters: "/characters",
	weapons: "/weapons",
	artifacts: "/artifacts",
	boss: "/boss",
	weeklyBoss: "/weekly-boss",
	consumables: "/consumables",
	food: "/food",
	potions: "/potions",
	materials: "/materials",
	bossMaterials: "/boss-material",
	list: "/list",
	icon: "/icon",
	card: "/card",
	circletOfLogos: "/circlet-of-logos",
};
