export const endpoints = {
	characters: "/characters",
	weapons: "/weapons",
	artifacts: "/artifacts",
	nations: "/nations",
	elements: "/elements",
	boss: "/boss",
	weeklyBoss: "/weekly-boss",
	consumables: "/consumables",
	food: "/food",
	potions: "/potions",
	materials: "/materials",
	bossMaterials: "/boss-material",
	cookingIngredients: "/cooking-ingredients",
	localSpecialties: "/local-specialties",
	characterAscension: "/character-ascension",
	commonAscension: "/common-ascension",
	characterExperience: "/character-experience",
	weaponAscension: "/weapon-ascension",
	weaponExperience: "/weapon-experience",
	talentBoss: "/talent-boss",
	talentBook: "/talent-book",
	list: "/list",
	icon: "/icon",
	card: "/card",
	gachaCard: "/gacha-card",
	circletOfLogos: "/circlet-of-logos",
};
